
- name: Login to Storage PFREST
  hosts: localhost
  vars_files:
    - storage_vault.yml
  vars:
    - myauthstring: "{{storage_username}}:{{storage_password}}"

  tasks:
    - name: 'Check if Variables passed'
      debug: msg="Please pass date_time_settings variable, example date_time_settings:"
      when: date_time_settings is undefined

    - meta: end_play
      when: date_time_settings is undefined

    - name: 'Get Session Token'
      uri:
        url: 'https://{{storage_ip}}/ConfigurationManager/v1/objects/sessions'
        method: POST
        body:
          {"authenticationTimeout":600}
        body_format: json
        headers:
          Connection: 'keep-alive'
          Cache-Control: 'no-store'
          Accept-Language: 'en'
          Authorization: 'Basic {{myauthstring | b64encode}}'
          Content-Type: 'application/json'
          Accept: 'application/json, text/plain, */*'
          Sec-Fetch-Site: 'same-origin'
          Sec-Fetch-Mode: 'cors'
          Sec-Fetch-Dest: 'empty'
        validate_certs: no
      register: token_response

    - name: 'Set Date and Time Settings'
      uri:
        url: 'https://{{storage_ip}}/ConfigurationManager/v1/objects/date-times/instance'
        method: POST
        body: {"isNtpEnabled":true,"ntpServerNames":["1.1.1.1"],"timeZoneId":"Europe/Berlin","systemTime":"2021-02-04T10:30:12Z","synchronizingLocalTime":"22:00","adjustsDaylightSavingTime":true,"synchronizesNow":true}
        body_format: json
        validate_certs: no
        headers:
          Accept: 'application/json'
          Content-Type: 'application/json'
          Authorization: 'Session {{token_response.json.token}}'
      register: result

    - name: 'Discard Session Token'
      uri:
        url: 'https://{{storage_ip}}/ConfigurationManager/v1/objects/sessions/{{token_response.json.sessionId}}'
        method: DELETE
        headers:
          Connection: 'keep-alive'
          Authorization: 'Session {{token_response.json.token}}'
          Content-Type: 'application/json'
          Accept: 'application/json, text/plain, */*'
          Sec-Fetch-Site: 'same-origin'
          Sec-Fetch-Mode: 'cors'
          Sec-Fetch-Dest: 'empty'
        validate_certs: no
      register: logout_response




